=== Schoggi0815/modul-151/adressen.xsd
<?xml version="1.0" encoding="ISO-8859-1"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:element name="adressliste">
		<xsd:complexType>
			<xsd:sequence>
			
				<xsd:element name="adresse" maxOccurs="unbounded">
					<xsd:complexType>
						<xsd:sequence>
						
							<xsd:element name="name" type="xsd:string"/>
							<xsd:element name="vorname" type="xsd:string"/>
							<xsd:element name="strasse" type="xsd:string"/>
							<xsd:element name="hausnummer" type="xsd:int"/>
							<xsd:element name="telefonnummer" type="xsd:string"/>

							<xsd:element name="nervensägen">
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element name="nervensäge" maxOccurs="unbounded" minOccurs="0">
											<xsd:complexType>
												<xsd:sequence>
													<xsd:element name="name" type="xsd:string"/>
													<xsd:element name="geburtsjahr" type="xsd:int"/>
												</xsd:sequence>
											</xsd:complexType>
										</xsd:element>
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>

						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== Schoggi0815/modul-151/adressen.xml
<?xml version="1.0" encoding="UTF-8"?>
<adressliste xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="adressen.xsd">

	<adresse>
		<name>muster</name>
		<vorname>hans</vorname>
		<strasse>mustergasse</strasse>
		<hausnummer>20</hausnummer>
		<telefonnummer>079 999 99 99</telefonnummer>
		<nervensägen>
			<nervensäge>
				<name>Kind</name>
				<geburtsjahr>1900</geburtsjahr>
			</nervensäge>
		</nervensägen>
	</adresse>

	<adresse>
		<name>studer</name>
		<vorname>eva</vorname>
		<strasse>stadtgasse</strasse>
		<hausnummer>15</hausnummer>
		<telefonnummer>079 999 99 99</telefonnummer>
		<nervensägen/>
	</adresse>

	<adresse>
		<name>foo</name>
		<vorname>bar</vorname>
		<strasse>foobar</strasse>
		<hausnummer>1</hausnummer>
		<telefonnummer>079 999 99 99</telefonnummer>
		<nervensägen/>
	</adresse>

	<adresse>
		<name>nice</name>
		<vorname>dope</vorname>
		<strasse>dopestreet</strasse>
		<hausnummer>69</hausnummer>
		<telefonnummer>079 999 99 99</telefonnummer>
		<nervensägen/>
	</adresse>
	
</adressliste>
